services:
  db: 
    image: postgres:16.2-bullseye
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: links 
    ports:
      - 5432:5432
  mongo:
    image: mongodb/mongodb-community-server:7.0.17-ubi9

